import type { Metadata } from 'next';

import { ThemeRegistry } from '@/modules/theme';

export const metadata: Metadata = {
	title: 'Cuisine',
	description: 'Generated by create next app', // TODO:
	viewport: {
		initialScale: 1,
		width: 'device-width',
	},
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body>
				<ThemeRegistry>{children}</ThemeRegistry>
			</body>
		</html>
	);
};

export default RootLayout;
